name: "🐛 Ho trovato un Bug"
description: "Hai trovato un bug? Segnalalo!"
title: "Nuovo Bug Segnalato"

body:
  - type: textarea
    id: what-happened
    label: "Cosa è successo?"
    description: "Descrivi il problema in dettaglio."
    placeholder: "Dì quello che vedi"
    required: true

  - type: select
    id: where
    label: "Dove è successo?"
    options:
      - Home
      - Pagina di ricerca
      - Profilo utente
      - Checkout
      - Altro
    required: true

  - type: checkboxes
    id: operating-systems
    label: "Sistemi operativi"
    options:
      - Windows 10
      - Windows 11
      - macOS Monterey
      - Ubuntu 22.04
      - ...
    required: true

  - type: select
    id: browser
    label: "Browser"
    options:
      - Chrome
      - Firefox
      - Safari
      - Edge
    required: true

  - type: checkboxes
    id: edition
    label: "Edizione"
    options:
      - Web
      - App mobile
      - App desktop
    required: true

  - type: text
    id: version
    label: "Versione"
    description: "Trova la versione in Impostazioni > Informazioni"
    required: true

  - type: textarea
    id: steps-to-reproduce
    label: "Passi per riprodurre"
    description: "Descrivi passo dopo passo come riprodurre il problema."
    required: true

  - type: file
    id: attachments
    label: "Allegati"

  - type: checkbox
    id: is-original-app
    label: "L'app è originale"
    description: "Sto utilizzando la versione ufficiale dell'app."
    required: true
