// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpdIyqwqFRbUehejdl0X-Sny8eOGx2gJ4',
    appId: '1:501212308848:web:050e5c1518e96298c39bb5',
    messagingSenderId: '501212308848',
    projectId: 'mybookshelf-c4888',
    authDomain: 'mybookshelf-c4888.firebaseapp.com',
    databaseURL: 'https://mybookshelf-c4888-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mybookshelf-c4888.appspot.com',
    measurementId: 'G-33XG9NMJ0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0UOhCYXWQtaupE6JV2yhQ8-VOUvisV5c',
    appId: '1:501212308848:android:d3ad2e3c82976388c39bb5',
    messagingSenderId: '501212308848',
    projectId: 'mybookshelf-c4888',
    databaseURL: 'https://mybookshelf-c4888-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mybookshelf-c4888.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh7UJ8vWoJTZgLRXFPCGAIP67IwUngK8A',
    appId: '1:501212308848:ios:521c4499aacd1615c39bb5',
    messagingSenderId: '501212308848',
    projectId: 'mybookshelf-c4888',
    databaseURL: 'https://mybookshelf-c4888-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mybookshelf-c4888.appspot.com',
    iosBundleId: 'com.riccardodebellini.mybookshelf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh7UJ8vWoJTZgLRXFPCGAIP67IwUngK8A',
    appId: '1:501212308848:ios:521c4499aacd1615c39bb5',
    messagingSenderId: '501212308848',
    projectId: 'mybookshelf-c4888',
    databaseURL: 'https://mybookshelf-c4888-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mybookshelf-c4888.appspot.com',
    iosBundleId: 'com.riccardodebellini.mybookshelf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpdIyqwqFRbUehejdl0X-Sny8eOGx2gJ4',
    appId: '1:501212308848:web:65dd415ffbffa184c39bb5',
    messagingSenderId: '501212308848',
    projectId: 'mybookshelf-c4888',
    authDomain: 'mybookshelf-c4888.firebaseapp.com',
    databaseURL: 'https://mybookshelf-c4888-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mybookshelf-c4888.appspot.com',
    measurementId: 'G-X1L4QEF9H4',
  );

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

}