name: Get Supabase Data Daily

on:
  schedule:
    - cron: '0 17 * * *'  # Runs at 5:00 PM everyday (UTC)
  workflow_dispatch:


jobs:
  get-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install @supabase/supabase-js
      - name: Get Data from Supabase
        run: |
          const { createClient } = require('@supabase/supabase-js')

          const supabaseUrl = 'https://wmztgdkplkomzdwileqx.supabase.co'
          const anonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtenRnZGtwbGtvbXpkd2lsZXF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjMwMzEzMzMsImV4cCI6MjAzODYwNzMzM30.eWwZMt4qe7JyuUMubB9gCxDQMKnKPGuQp-k1Y1U5NpI'

          const supabase = createClient(supabaseUrl, anonKey)

          // Replace 'your_table_name' and 'select_query' with your actual values
          const { data, error } = await supabase.from('profile').select()

          if (error) {
            console.error('Error fetching data:', error)
          } else {
            console.log('Fetched data:', data)
          }
  
